apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: common
spec:
  chart:
    spec:
      chart: hedera-mirror-common
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      version: '0.84.0-rc1'
  dependsOn:
    - name: testkube
      namespace: testkube
  install:
    crds: CreateReplace
  interval: 1m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 10
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    loki:
      singleBinary:
        resources:
          limits:
            memory: 512Mi
    prometheus:
      prometheus:
        prometheusSpec:
          externalLabels:
            cluster: preprod
          remoteWrite:
            - basicAuth:
                password:
                  key: password
                  name: grafana-cloud
                username:
                  key: username
                  name: grafana-cloud
              url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
              writeRelabelConfigs:
                - action: keep
                  regex: .*(graphql|grpc|importer|monitor|rest|rosetta|traefik|web3)$
                  sourceLabels: [job]
                - action: drop
                  regex: (api_.+_bucket|executor.*|lettuce_.*_bucket|traefik_.+_bucket)
                  sourceLabels: [__name__]
          replicaExternalLabelName: __replica__
    testkube:
      enabled: true
      test:
        gitBranch: main
        target:
          namespace: performance
    traefik:
      service:
        annotations:
          cloud.google.com/neg: '{ "exposed_ports":{ "443":{"name": "mirrornode-preprod"} } }'

