apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mirror
resources:
- ../../base/common
- ../../base/testkube
- helmrelease.yaml
- sealed-secret.yaml
- sealed-secret-grafana-cloud.yaml
patches:
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: testkube
      namespace: testkube
    spec:
      chart:
        spec:
          version: 1.11.174
  target:
    kind: HelmRelease
    name: testkube
