apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: performance
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.82.0-rc1'
  dependsOn:
    - name: mirror
      namespace: common
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: true
    timeout: 25m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    grpc:
      resources:
        requests:
          cpu: 1000m
          memory: 1024Mi
    importer:
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "OTHER"
        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_SIDECAR_ENABLED: "true"
        HEDERA_MIRROR_IMPORTER_DOWNLOADER_THREADS: "35"
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 2000m
          memory: 4Gi
    monitor:
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "OTHER"
      prometheusRules:
        MonitorPublishErrors:
          enabled: false
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    postgresql:
      enabled: false
    test:
      enabled: true
      config:
        hedera:
          mirror:
            test:
              acceptance:
                network: OTHER

