apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hedera-mirror-node
  namespace: integration
spec:
  ignore: |
    /*
    !/charts
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/hashgraph/hedera-mirror-node.git
